name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]

jobs:
    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Expressions
              id: expression
              run: |
                echo ${{1}}
                echo ${{ 'This is a string' }}
                echo ${{null}}
                echo ${{false}}
                echo ${{1 > 2}}
                echo ${{ 'string' == 'String'}}
            - name: Dump Contexts
              run: |
                echo '${{ toJson(github)}}'
                echo '${{ toJson(job)}}'
                echo '${{ toJson(secrets)}}'
                echo '${{ toJson(steps)}}'
                echo '${{ toJson(runner)}}'